language: java
sudo: false

jdk:
  - openjdk11

install: "mvn -P ci clean install --quiet -DskipTests -Dcheckstyle.skip=true -Dmaven.javadoc.skip=true -Dgpg.skip=true"

branches:
  only:
    - master

script: "mvn clean verify -Dgpg.skip=true"
after_success:
- mvn jacoco:report coveralls:report --debug